/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2026-02-05 23:09:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import org.Ocean_View.Connection.DatabaseConnection;
import java.sql.*;

public final class AddRoom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("org.Ocean_View.Connection.DatabaseConnection");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Add New Room</title>\r\n");
      out.write("    <!-- Bootstrap CSS link -->\r\n");
      out.write("    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome for icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #0073bb;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        label {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        input, select, textarea, button {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        input::placeholder, textarea::placeholder {\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        textarea {\r\n");
      out.write("            resize: vertical;\r\n");
      out.write("            min-height: 100px;\r\n");
      out.write("        }\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Drag and Drop Styling */\r\n");
      out.write("        .drop-zone {\r\n");
      out.write("            border: 2px dashed #0073bb;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .drop-zone:hover, .drop-zone.dragover {\r\n");
      out.write("            background-color: #e9f7fe;\r\n");
      out.write("            border-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .drop-zone i {\r\n");
      out.write("            font-size: 48px;\r\n");
      out.write("            color: #0073bb;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .drop-zone p {\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            color: #666;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .file-input-label {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background-color: #0073bb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .file-input-label:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .file-input {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Preview Container */\r\n");
      out.write("        .preview-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .image-preview {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 120px;\r\n");
      out.write("            height: 120px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 2px 5px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .image-preview img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remove-image {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 5px;\r\n");
      out.write("            right: 5px;\r\n");
      out.write("            background-color: rgba(255,0,0,0.7);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            width: 24px;\r\n");
      out.write("            height: 24px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remove-image:hover {\r\n");
      out.write("            background-color: rgba(255,0,0,0.9);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Selected files info */\r\n");
      out.write("        .selected-files-info {\r\n");
      out.write("            background-color: #e9f7fe;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            border-left: 4px solid #0073bb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Buttons */\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background-color: #0073bb;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 12px 30px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            width: auto;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-btn {\r\n");
      out.write("            background-color: #6c757d;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: auto;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-btn:hover {\r\n");
      out.write("            background-color: #545b62;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            color: #0073bb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a:hover {\r\n");
      out.write("            color: #5196c1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Progress bar */\r\n");
      out.write("        .progress-container {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .progress {\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .progress-bar {\r\n");
      out.write("            background-color: #0073bb;\r\n");
      out.write("            transition: width 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1><i class=\"fas fa-plus-circle\"></i> Add New Room</h1>\r\n");
      out.write("\r\n");
      out.write("        <form id=\"addRoomForm\" action=\"/Admin/AddRoom\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"description\">Description:</label>\r\n");
      out.write("                <textarea id=\"description\" name=\"description\" placeholder=\"Enter Room Description\" required></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"noOfPeople\">No of People:</label>\r\n");
      out.write("                <input type=\"text\" id=\"noOfPeople\" name=\"noOfPeople\" placeholder=\"Enter No of People\" required min=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"facilities\">Facilities:</label>\r\n");
      out.write("                <input type=\"text\" id=\"facilities\" name=\"facilities\" placeholder=\"Enter Facilities (comma separated)\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"fine\">Fine:</label>\r\n");
      out.write("                <input type=\"number\" id=\"fine\" name=\"fine\" placeholder=\"Enter Fine\" step=\"0.01\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"rules\">Rules:</label>\r\n");
      out.write("                <textarea id=\"rules\" name=\"rules\" placeholder=\"Enter Rules\" required></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"roomType\">Room Type:</label>\r\n");
      out.write("                <select id=\"roomType\" name=\"roomType\" required>\r\n");
      out.write("                    ");

                    Connection conn = null;
                    PreparedStatement stmt = null;
                    ResultSet rs = null;

                    try {
                        conn = DatabaseConnection.getConnection();
                        String query = "SELECT roomCategory FROM room_type";
                        stmt = conn.prepareStatement(query);
                        rs = stmt.executeQuery();

                        while (rs.next()) {
                            String categoryName = rs.getString("roomCategory");
                    
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( categoryName );
      out.write('"');
      out.write('>');
      out.print( categoryName );
      out.write("</option>\r\n");
      out.write("                    ");

                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    } finally {
                        try {
                            if (rs != null) rs.close();
                            if (stmt != null) stmt.close();
                            if (conn != null) conn.close();
                        } catch (SQLException ignore) {}
                    }
                    
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"price\">Rent per Day:</label>\r\n");
      out.write("                <input type=\"number\" id=\"price\" name=\"price\" placeholder=\"Enter Rent per Day\" step=\"0.01\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Multiple Image Upload with Drag & Drop -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Room Images (Multiple):</label>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"drop-zone\" id=\"dropZone\">\r\n");
      out.write("                    <i class=\"fas fa-cloud-upload-alt\"></i>\r\n");
      out.write("                    <p>Drag & drop images here</p>\r\n");
      out.write("                    <p>or</p>\r\n");
      out.write("                    <label class=\"file-input-label\">\r\n");
      out.write("                        <i class=\"fas fa-folder-open\"></i> Browse Files\r\n");
      out.write("                        <input type=\"file\" id=\"roomImages\" name=\"roomImages\" class=\"file-input\" accept=\"image/*\" multiple>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <p class=\"text-muted\" style=\"margin-top: 10px;\">\r\n");
      out.write("                        <small>Supported formats: JPG, PNG, GIF. Max file size: 5MB</small>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"selectedFilesInfo\" class=\"selected-files-info\" style=\"display: none;\">\r\n");
      out.write("                    <p id=\"filesCount\">0 files selected</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Image Preview Container -->\r\n");
      out.write("                <div id=\"imagePreview\" class=\"preview-container\"></div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Progress Bar (Optional) -->\r\n");
      out.write("                <div class=\"progress-container\" id=\"progressContainer\">\r\n");
      out.write("                    <div class=\"progress\">\r\n");
      out.write("                        <div class=\"progress-bar\" id=\"progressBar\" role=\"progressbar\" style=\"width: 0%;\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p id=\"progressText\" class=\"text-center mt-2\">Uploading...</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"button-container\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn-primary\">\r\n");
      out.write("                    <i class=\"fas fa-save\"></i> Add Room\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" class=\"back-btn\" onclick=\"window.history.back();\">\r\n");
      out.write("                    <i class=\"fas fa-arrow-left\"></i> Back\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"/Admin/ManageRooms\">\r\n");
      out.write("            <i class=\"fas fa-eye\"></i> View Added Rooms\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS and dependencies -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom JavaScript for Drag & Drop -->\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            const dropZone = document.getElementById('dropZone');\r\n");
      out.write("            const fileInput = document.getElementById('roomImages');\r\n");
      out.write("            const imagePreview = document.getElementById('imagePreview');\r\n");
      out.write("            const selectedFilesInfo = document.getElementById('selectedFilesInfo');\r\n");
      out.write("            const filesCount = document.getElementById('filesCount');\r\n");
      out.write("            const progressContainer = document.getElementById('progressContainer');\r\n");
      out.write("            const progressBar = document.getElementById('progressBar');\r\n");
      out.write("            const progressText = document.getElementById('progressText');\r\n");
      out.write("\r\n");
      out.write("            let uploadedFiles = [];\r\n");
      out.write("\r\n");
      out.write("            // Prevent default drag behaviors\r\n");
      out.write("            ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {\r\n");
      out.write("                dropZone.addEventListener(eventName, preventDefaults, false);\r\n");
      out.write("                document.body.addEventListener(eventName, preventDefaults, false);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            function preventDefaults(e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                e.stopPropagation();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Highlight drop zone when item is dragged over it\r\n");
      out.write("            ['dragenter', 'dragover'].forEach(eventName => {\r\n");
      out.write("                dropZone.addEventListener(eventName, highlight, false);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            ['dragleave', 'drop'].forEach(eventName => {\r\n");
      out.write("                dropZone.addEventListener(eventName, unhighlight, false);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            function highlight(e) {\r\n");
      out.write("                dropZone.classList.add('dragover');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function unhighlight(e) {\r\n");
      out.write("                dropZone.classList.remove('dragover');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Handle dropped files\r\n");
      out.write("            dropZone.addEventListener('drop', handleDrop, false);\r\n");
      out.write("\r\n");
      out.write("            function handleDrop(e) {\r\n");
      out.write("                const dt = e.dataTransfer;\r\n");
      out.write("                const files = dt.files;\r\n");
      out.write("                handleFiles(files);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Handle file input change\r\n");
      out.write("            fileInput.addEventListener('change', function() {\r\n");
      out.write("                handleFiles(this.files);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Handle files from both drag & drop and file input\r\n");
      out.write("            function handleFiles(files) {\r\n");
      out.write("                [...files].forEach(file => {\r\n");
      out.write("                    if (file.type.startsWith('image/')) {\r\n");
      out.write("                        uploadedFiles.push(file);\r\n");
      out.write("                        previewImage(file);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                updateFilesInfo();\r\n");
      out.write("                // Clear file input to allow selecting same files again\r\n");
      out.write("                fileInput.value = '';\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Create image preview\r\n");
      out.write("            function previewImage(file) {\r\n");
      out.write("                const reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("                reader.onload = function(e) {\r\n");
      out.write("                    const previewDiv = document.createElement('div');\r\n");
      out.write("                    previewDiv.className = 'image-preview';\r\n");
      out.write("\r\n");
      out.write("                    const img = document.createElement('img');\r\n");
      out.write("                    img.src = e.target.result;\r\n");
      out.write("                    img.alt = file.name;\r\n");
      out.write("\r\n");
      out.write("                    const removeBtn = document.createElement('button');\r\n");
      out.write("                    removeBtn.type = 'button';\r\n");
      out.write("                    removeBtn.className = 'remove-image';\r\n");
      out.write("                    removeBtn.innerHTML = '<i class=\"fas fa-times\"></i>';\r\n");
      out.write("                    removeBtn.title = 'Remove image';\r\n");
      out.write("\r\n");
      out.write("                    removeBtn.onclick = function() {\r\n");
      out.write("                        // Remove file from array\r\n");
      out.write("                        const index = uploadedFiles.indexOf(file);\r\n");
      out.write("                        if (index > -1) {\r\n");
      out.write("                            uploadedFiles.splice(index, 1);\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        // Remove preview\r\n");
      out.write("                        previewDiv.remove();\r\n");
      out.write("                        updateFilesInfo();\r\n");
      out.write("                    };\r\n");
      out.write("\r\n");
      out.write("                    previewDiv.appendChild(img);\r\n");
      out.write("                    previewDiv.appendChild(removeBtn);\r\n");
      out.write("                    imagePreview.appendChild(previewDiv);\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                reader.readAsDataURL(file);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Update selected files information\r\n");
      out.write("            function updateFilesInfo() {\r\n");
      out.write("                const count = uploadedFiles.length;\r\n");
      out.write("\r\n");
      out.write("                // FIXED: Removed JSP EL syntax and used pure JavaScript\r\n");
      out.write("                const pluralSuffix = count !== 1 ? 's' : '';\r\n");
      out.write("                filesCount.textContent = count + ' file' + pluralSuffix + ' selected';\r\n");
      out.write("\r\n");
      out.write("                selectedFilesInfo.style.display = count > 0 ? 'block' : 'none';\r\n");
      out.write("\r\n");
      out.write("                // Update form data before submission\r\n");
      out.write("                updateFormData();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Update form data with files\r\n");
      out.write("            function updateFormData() {\r\n");
      out.write("                // Create a new FormData object\r\n");
      out.write("                const form = document.getElementById('addRoomForm');\r\n");
      out.write("                const formData = new FormData(form);\r\n");
      out.write("\r\n");
      out.write("                // Clear existing files from form data\r\n");
      out.write("                formData.delete('roomImages');\r\n");
      out.write("\r\n");
      out.write("                // Add all selected files\r\n");
      out.write("                uploadedFiles.forEach((file, index) => {\r\n");
      out.write("                    formData.append('roomImages', file);\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // Update form submission\r\n");
      out.write("                form.dataset.formData = JSON.stringify(Array.from(formData.entries()));\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Handle form submission with AJAX for progress tracking\r\n");
      out.write("            const form = document.getElementById('addRoomForm');\r\n");
      out.write("            form.addEventListener('submit', function(e) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("                if (uploadedFiles.length === 0) {\r\n");
      out.write("                    alert('Please select at least one image for the room.');\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // Show progress bar\r\n");
      out.write("                progressContainer.style.display = 'block';\r\n");
      out.write("                progressBar.style.width = '0%';\r\n");
      out.write("                progressText.textContent = 'Uploading...';\r\n");
      out.write("\r\n");
      out.write("                // Create FormData\r\n");
      out.write("                const formData = new FormData(this);\r\n");
      out.write("\r\n");
      out.write("                // Add all uploaded files\r\n");
      out.write("                uploadedFiles.forEach(file => {\r\n");
      out.write("                    formData.append('roomImages', file);\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                // Send AJAX request\r\n");
      out.write("                const xhr = new XMLHttpRequest();\r\n");
      out.write("\r\n");
      out.write("                xhr.upload.addEventListener('progress', function(e) {\r\n");
      out.write("                    if (e.lengthComputable) {\r\n");
      out.write("                        const percentComplete = (e.loaded / e.total) * 100;\r\n");
      out.write("                        progressBar.style.width = percentComplete + '%';\r\n");
      out.write("                        progressText.textContent = 'Uploading: ' + Math.round(percentComplete) + '%';\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                xhr.addEventListener('load', function() {\r\n");
      out.write("                    if (xhr.status === 200) {\r\n");
      out.write("                        progressBar.style.width = '100%';\r\n");
      out.write("                        progressText.textContent = 'Upload complete!';\r\n");
      out.write("\r\n");
      out.write("                        // Handle success response\r\n");
      out.write("                        try {\r\n");
      out.write("                            const response = JSON.parse(xhr.responseText);\r\n");
      out.write("                            if (response.success) {\r\n");
      out.write("                                alert('Room added successfully with ID: ' + response.roomId);\r\n");
      out.write("                                window.location.href = '/Admin/AddRoom.jsp';\r\n");
      out.write("                            } else {\r\n");
      out.write("                                alert('Error: ' + response.message);\r\n");
      out.write("                            }\r\n");
      out.write("                        } catch (e) {\r\n");
      out.write("                            // If response is not JSON, assume it's HTML with script tag\r\n");
      out.write("                            document.open();\r\n");
      out.write("                            document.write(xhr.responseText);\r\n");
      out.write("                            document.close();\r\n");
      out.write("                        }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert('Error uploading files. Please try again.');\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // Hide progress bar after 2 seconds\r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        progressContainer.style.display = 'none';\r\n");
      out.write("                    }, 2000);\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                xhr.addEventListener('error', function() {\r\n");
      out.write("                    alert('Error uploading files. Please check your connection.');\r\n");
      out.write("                    progressContainer.style.display = 'none';\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                xhr.open('POST', this.action);\r\n");
      out.write("                xhr.send(formData);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Initialize\r\n");
      out.write("            updateFilesInfo();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
