/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2026-02-02 06:32:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import org.Ocean_View.Connection.DatabaseConnection;
import java.sql.*;

public final class AddRoom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("org.Ocean_View.Connection.DatabaseConnection");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Add New Vehicle</title>\r\n");
      out.write("    <!-- Bootstrap CSS link -->\r\n");
      out.write("    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #0073bb;\r\n");
      out.write("        }\r\n");
      out.write("        label {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 1rem;  /* Standard size for labels */\r\n");
      out.write("        }\r\n");
      out.write("        input, select, button {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px;  /* Increased padding for better visibility */\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-size: 1rem; /* Standard text size */\r\n");
      out.write("        }\r\n");
      out.write("        input::placeholder {\r\n");
      out.write("            font-size: 1rem; /* Ensures placeholder text follows standard size */\r\n");
      out.write("        }\r\n");
      out.write("        button {\r\n");
      out.write("            background-color: #0073bb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background-color: #5196c1;\r\n");
      out.write("        }\r\n");
      out.write("        .back-btn {\r\n");
      out.write("            background-color: #0073bb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .back-btn:hover {\r\n");
      out.write("            background-color: #5196c1;\r\n");
      out.write("        }\r\n");
      out.write("        a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            color: #0073bb;\r\n");
      out.write("        }\r\n");
      out.write("        a:hover {\r\n");
      out.write("            color: #5196c1;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1>Add New Vehicle</h1>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"/Mega_City/VehicleSaveServlet\" method=\"post\" >\r\n");
      out.write("            <label for=\"vehicle_name\">Vehicle Name:</label>\r\n");
      out.write("            <input type=\"text\" id=\"vehicle_name\" name=\"vehicle_name\" placeholder=\"Enter Vehicle Name\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"vehicle_year\">Vehicle Year:</label>\r\n");
      out.write("            <input type=\"text\" id=\"vehicle_year\" name=\"vehicle_year\" placeholder=\"Enter Vehicle Year\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"brand_name\">Brand Name:</label>\r\n");
      out.write("            <input type=\"text\" id=\"brand_name\" name=\"brand_name\" placeholder=\"Enter Brand Name\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"condition\">Condition:</label>\r\n");
      out.write("            <input type=\"text\" id=\"condition\" name=\"condition\" placeholder=\"Enter Condition\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"mileage\">Mileage:</label>\r\n");
      out.write("            <input type=\"text\" id=\"mileage\" name=\"mileage\" placeholder=\"Enter Mileage\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"color\">Color:</label>\r\n");
      out.write("            <input type=\"text\" id=\"color\" name=\"color\" placeholder=\"Enter Vehicle Color\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"type\">Vehicle Type:</label>\r\n");
      out.write("            <select id=\"type\" name=\"type\" required>\r\n");
      out.write("                ");

                Connection conn = null;
                PreparedStatement stmt = null;
                ResultSet rs = null;

                try {
                    conn = DatabaseConnection.getConnection(); // Get the database connection
                    String query = "SELECT roomCategory FROM room_type"; // Query to fetch vehicle categories
                    stmt = conn.prepareStatement(query);
                    rs = stmt.executeQuery();

                    while (rs.next()) {
                        String categoryName = rs.getString("roomCategory");
                
      out.write("\r\n");
      out.write("                    <option value=\"");
      out.print( categoryName );
      out.write('"');
      out.write('>');
      out.print( categoryName );
      out.write("</option>\r\n");
      out.write("                ");

                    }
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (rs != null) rs.close();
                        if (stmt != null) stmt.close();
                        if (conn != null) conn.close();
                    } catch (SQLException ignore) {}
                }
                
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("            <br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"rent_per_day\">Rent per Day:</label>\r\n");
      out.write("            <input type=\"text\" id=\"rent_per_day\" name=\"rent_per_day\" placeholder=\"Enter Rent per Day\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"vehicle_image\">Vehicle Image:</label>\r\n");
      out.write("            <input type=\"file\" id=\"vehicle_image\" name=\"vehicle_image\" accept=\"image/*\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Submit</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"/Mega_City/VehicleRetrieveServlet\">View Added Vehicles</a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Back button -->\r\n");
      out.write("        <button class=\"back-btn\" onclick=\"window.history.back();\">Back</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS and dependencies -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
