/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2026-02-05 21:31:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Admin Panel</title>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      font-family: Arial, sans-serif;\r\n");
      out.write("      background-color: #f7f7f7;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .header-content {\r\n");
      out.write("      background-color: #f5f5f5;\r\n");
      out.write("      padding: 10px 20px;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo {\r\n");
      out.write("      background-color: #D63A36;\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      font-size: 18px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .header-date {\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-menu .profile img {\r\n");
      out.write("      width: 40px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Sidebar Styles */\r\n");
      out.write("    .sidebar {\r\n");
      out.write("      background-color: #2d3436;\r\n");
      out.write("      color: white;\r\n");
      out.write("      width: 230px;\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      padding-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul {\r\n");
      out.write("      list-style-type: none;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul li {\r\n");
      out.write("      padding: 15px 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul li a {\r\n");
      out.write("      color: white;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul li a:hover {\r\n");
      out.write("      background-color: #333;\r\n");
      out.write("      border-left: 4px solid #D63A36;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul .submenu {\r\n");
      out.write("      display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul li:hover > .submenu {\r\n");
      out.write("      display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Dashboard Cards */\r\n");
      out.write("    .page {\r\n");
      out.write("      margin-left: 250px;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container-fluid {\r\n");
      out.write("      display: grid;\r\n");
      out.write("      grid-template-columns: repeat(3, 1fr);\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      padding: 30px;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card i {\r\n");
      out.write("      font-size: 40px;\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card:nth-child(1) {\r\n");
      out.write("      background-color: #bdc3c7;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card:nth-child(2) {\r\n");
      out.write("      background-color: #e74c3c;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card:nth-child(3) {\r\n");
      out.write("      background-color: #3498db;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card:nth-child(4) {\r\n");
      out.write("      background-color: #f39c12;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card:nth-child(5) {\r\n");
      out.write("      background-color: #2ecc71;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Responsive adjustments */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("      .container-fluid {\r\n");
      out.write("        grid-template-columns: 1fr;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .sidebar {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        position: relative;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .page {\r\n");
      out.write("        margin-left: 0;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <header id=\"header\">\r\n");
      out.write("    <div class=\"logo pull-left\"> Admin Portal</div>\r\n");
      out.write("    <div class=\"header-content\">\r\n");
      out.write("      <div class=\"header-date pull-left\">\r\n");
      out.write("        <strong></strong>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"pull-right clearfix\">\r\n");
      out.write("        <ul class=\"info-menu list-inline list-unstyled\">\r\n");
      out.write("          <li class=\"profile\">\r\n");
      out.write("            <a href=\"#\" data-toggle=\"dropdown\" class=\"toggle\" aria-expanded=\"false\">\r\n");
      out.write("              <span> <i class=\"caret\"></i></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a href=\"profile.php\"><i class=\"glyphicon glyphicon-user\"></i> Profile</a></li>\r\n");
      out.write("              <li><a href=\"edit_account.php\"><i class=\"glyphicon glyphicon-cog\"></i> Settings</a></li>\r\n");
      out.write("              <li class=\"last\"><a href=\"logout.php\"><i class=\"glyphicon glyphicon-off\"></i> Logout</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"sidebar\">\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li><a href=\"/Admin/Dashboard.jsp\"><i class=\"glyphicon glyphicon-home\"></i> Dashboard</a></li>\r\n");
      out.write("      <li><a href=\"#\" class=\"submenu-toggle\"><i class=\"glyphicon glyphicon-user\"></i> User Management</a>\r\n");
      out.write("        <ul class=\"nav submenu\">\r\n");
      out.write("\r\n");
      out.write("          <li><a href=\"/Admin/ManageCustomers\">Manage Customer</a></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"/Mega_City/ManageVehicleTypesServlet\"><i class=\"glyphicon glyphicon-indent-left\"></i> Manage Categories</a>\r\n");
      out.write("      <ul class=\"nav submenu\">\r\n");
      out.write("        <li><a href=\"/Admin/AddNewRoomTypes.html\">Add Categories</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" class=\"submenu-toggle\"><i class=\"glyphicon glyphicon-th-large\"></i> Products</a>\r\n");
      out.write("        <ul class=\"nav submenu\">\r\n");
      out.write("          <li><a href=\"/Admin/AddNewRoomTypes.html\">Manage Room Types</a></li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("      <li>\r\n");
      out.write("    <a href=\"/Admin/ViewAllBookings\" class=\"submenu-toggle\">\r\n");
      out.write("        <i class=\"glyphicon glyphicon-list-alt\"></i> View All Bookings\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <li><a href=\"/Admin/Signing.jsp\" class=\"submenu-toggle\"><i class=\"fas fa-sign-out-alt\"></i> Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"page\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("    <a href=\"/Admin/EditProfile\" class=\"card\">\r\n");
      out.write("      <i class=\"glyphicon glyphicon-user\"></i>  Edit Profile\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"/Admin/AddNewRoomTypes.html\" class=\"card\">\r\n");
      out.write("      <i class=\"glyphicon glyphicon-shopping-cart\"></i>  Manage Room Types\r\n");
      out.write("    </a>\r\n");
      out.write("    <a href=\"/Admin/AddRoom.jsp\" class=\"card\">\r\n");
      out.write("      <i class=\"glyphicon glyphicon-th\"></i>  Manage Rooms\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
