/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2026-01-29 21:02:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Signing_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Customer Login Form</title>\r\n");
      out.write("  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css'>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" id=\"container\">\r\n");
      out.write("	<!-- Sign-Up Container -->\r\n");
      out.write("	<div class=\"form-container sign-up-container\">\r\n");
      out.write("		<form id=\"signupForm\" action=\"/Admin/Register\" method=\"POST\">\r\n");
      out.write("                    <!-- HTML -->\r\n");
      out.write("			<h1>Create Account</h1><br>\r\n");
      out.write("			<div class=\"social-container\">\r\n");
      out.write("				<a href=\"#\" class=\"social\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("				<a href=\"#\" class=\"social\"><i class=\"fab fa-google-plus-g\"></i></a>\r\n");
      out.write("				<a href=\"#\" class=\"social\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<span>or use your email for registration</span>\r\n");
      out.write("			<input type=\"text\" id=\"firstName\" name=\"firstname\" placeholder=\"First Name\" required />\r\n");
      out.write("			<input type=\"text\" id=\"lastName\" name=\"lastname\" placeholder=\"Last Name\" required />\r\n");
      out.write("			<input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Email\" required />\r\n");
      out.write("			<input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Password\" required />\r\n");
      out.write("			<input type=\"password\" id=\"confirmPassword\" name=\"confirmpassword\" placeholder=\"Confirm Password\" required />\r\n");
      out.write("			<input type=\"text\" id=\"contactNumber\" name=\"contact_number\" placeholder=\"Contact Number\" required />\r\n");
      out.write("                        <input type=\"text\" id=\"nic\" name=\"nic\" placeholder=\"NIC\" required />\r\n");
      out.write("			<button type=\"submit\" name=\"register\" value=\"register\">Sign Up</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Sign-In Container -->\r\n");
      out.write("	<div class=\"form-container sign-in-container\">\r\n");
      out.write("		<form id=\"signinForm\" action=\"/Admin/Login\" method=\"post\">\r\n");
      out.write("			<h1>Sign in</h1><br>\r\n");
      out.write("			<div class=\"social-container\">\r\n");
      out.write("				<a href=\"#\" class=\"social\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("				<a href=\"#\" class=\"social\"><i class=\"fab fa-google-plus-g\"></i></a>\r\n");
      out.write("				<a href=\"#\" class=\"social\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<span>or use your account</span>\r\n");
      out.write("			<input type=\"email\" id=\"signinEmail\" name=\"email\" placeholder=\"Email\" required />\r\n");
      out.write("			<input type=\"password\" id=\"signinPassword\" name=\"password\" placeholder=\"Password\" required />\r\n");
      out.write("			<a href=\"recover_psw.html\">Forgot your password?</a>\r\n");
      out.write("			<button type=\"submit\">Sign In</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Overlay Container -->\r\n");
      out.write("	<div class=\"overlay-container\">\r\n");
      out.write("		<div class=\"overlay\">\r\n");
      out.write("			<div class=\"overlay-panel overlay-left\">\r\n");
      out.write("				<h1>Welcome Back!</h1><br>\r\n");
      out.write("				<p>To keep connected with us please login with your personal info</p><br>\r\n");
      out.write("				<button class=\"ghost\" id=\"signIn\">Sign In</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"overlay-panel overlay-right\">\r\n");
      out.write("				<h1>Hello, Friend!</h1><br>\r\n");
      out.write("				<p>Enter your personal details and start journey with us</p><br>\r\n");
      out.write("				<button class=\"ghost\" id=\"signUp\">Sign Up</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <p>\r\n");
      out.write("        Brought to you by <a href=\"https://Mega-City.com\" target=\"_blank\">Ocean View Resort</a> - Your go-to Ocean View for all your\r\n");
      out.write("        Resort Room needs.\r\n");
      out.write("    </p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("const signUpButton = document.getElementById('signUp');\r\n");
      out.write("const signInButton = document.getElementById('signIn');\r\n");
      out.write("const container = document.getElementById('container');\r\n");
      out.write("\r\n");
      out.write("signUpButton.addEventListener('click', () => {\r\n");
      out.write("	container.classList.add(\"right-panel-active\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("signInButton.addEventListener('click', () => {\r\n");
      out.write("	container.classList.remove(\"right-panel-active\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"signupForm\").addEventListener(\"submit\", function (event) {\r\n");
      out.write("    let isValid = true;\r\n");
      out.write("\r\n");
      out.write("    // Validate first name\r\n");
      out.write("    const firstName = document.getElementById(\"firstName\").value.trim();\r\n");
      out.write("    if (!/^[A-Za-z]{2,}$/.test(firstName)) {\r\n");
      out.write("        alert(\"First name must be at least 2 characters and contain only letters.\");\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Validate last name\r\n");
      out.write("    const lastName = document.getElementById(\"lastName\").value.trim();\r\n");
      out.write("    if (!/^[A-Za-z]{2,}$/.test(lastName)) {\r\n");
      out.write("        alert(\"Last name must be at least 2 characters and contain only letters.\");\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Validate email\r\n");
      out.write("    const email = document.getElementById(\"email\").value.trim();\r\n");
      out.write("    if (!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email)) {\r\n");
      out.write("        alert(\"Please enter a valid email address.\");\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Validate contact number\r\n");
      out.write("    const contactNumber = document.getElementById(\"contactNumber\").value.trim();\r\n");
      out.write("    if (!/^\\d{10}$/.test(contactNumber)) {\r\n");
      out.write("        alert(\"Contact number must be 10 digits.\");\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Validate password and confirm password\r\n");
      out.write("    const password = document.getElementById(\"password\").value;\r\n");
      out.write("    const confirmPassword = document.getElementById(\"confirmPassword\").value;\r\n");
      out.write("    if (password.length < 6) {\r\n");
      out.write("        alert(\"Password must be at least 6 characters long.\");\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("    if (password !== confirmPassword) {\r\n");
      out.write("        alert(\"Passwords do not match.\");\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Prevent form submission if any validation fails\r\n");
      out.write("    if (!isValid) {\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
