/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2026-02-04 20:26:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Customer;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import org.Ocean_View.Customer.Entity.Booking;

public final class BookingSuccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("org.Ocean_View.Customer.Entity.Booking");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Retrieve the booking object stored by the servlet
    Booking booking = (Booking) session.getAttribute("lastBooking");

    // Redirect to home if someone tries to access this page directly without a booking
    if (booking == null) {
        response.sendRedirect("/Customer/Signing.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Booking Confirmed - Ocean View</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root { --primary: #2c3e50; --success: #27ae60; --light: #f8f9fa; }\r\n");
      out.write("        body { font-family: 'Segoe UI', sans-serif; background: #eef2f3; display: flex; justify-content: center; padding: 40px 20px; }\r\n");
      out.write("\r\n");
      out.write("        .receipt-card {\r\n");
      out.write("            background: white; width: 100%; max-width: 600px;\r\n");
      out.write("            border-radius: 15px; box-shadow: 0 15px 35px rgba(0,0,0,0.1); overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header { background: var(--success); color: white; padding: 30px; text-align: center; }\r\n");
      out.write("        .header i { font-size: 50px; margin-bottom: 10px; }\r\n");
      out.write("\r\n");
      out.write("        .content { padding: 30px; }\r\n");
      out.write("        .section-title { border-bottom: 2px solid var(--light); padding-bottom: 10px; margin-bottom: 20px; color: var(--primary); font-size: 1.2rem; }\r\n");
      out.write("\r\n");
      out.write("        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }\r\n");
      out.write("        .info-item label { display: block; color: #888; font-size: 0.85rem; text-transform: uppercase; margin-bottom: 5px; }\r\n");
      out.write("        .info-item span { font-weight: 600; color: var(--primary); }\r\n");
      out.write("\r\n");
      out.write("        .total-banner { background: var(--light); padding: 20px; border-radius: 10px; text-align: center; margin-top: 20px; }\r\n");
      out.write("        .total-banner h2 { margin: 0; color: var(--success); }\r\n");
      out.write("\r\n");
      out.write("        .actions { display: flex; gap: 10px; padding: 0 30px 30px; }\r\n");
      out.write("        .btn { flex: 1; padding: 12px; border-radius: 8px; text-align: center; text-decoration: none; font-weight: bold; transition: 0.3s; }\r\n");
      out.write("        .btn-print { background: var(--primary); color: white; border: none; cursor: pointer; }\r\n");
      out.write("        .btn-home { background: #dcdde1; color: var(--primary); }\r\n");
      out.write("\r\n");
      out.write("        @media print { .actions, .header i { display: none; } .receipt-card { box-shadow: none; border: 1px solid #ccc; } }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"receipt-card\">\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("        <h1>Booking Confirmed!</h1>\r\n");
      out.write("        <p>Thank you, ");
      out.print( booking.getCustomerFirstName() + " " + booking.getCustomerLastName());
      out.write("</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"section-title\">Reservation Details</div>\r\n");
      out.write("        <div class=\"info-grid\">\r\n");
      out.write("            <div class=\"info-item\">\r\n");
      out.write("                <label>Booking ID</label>\r\n");
      out.write("                <span>");
      out.print( booking.getUniqueId() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-item\">\r\n");
      out.write("                <label>Room ID</label>\r\n");
      out.write("                <span>");
      out.print( booking.getRoomId() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-item\">\r\n");
      out.write("                <label>Category</label>\r\n");
      out.write("                <span>");
      out.print( booking.getRoomCategory() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-item\">\r\n");
      out.write("                <label>Stay Duration</label>\r\n");
      out.write("                <span>");
      out.print( booking.getNoOfDays() );
      out.write(" Night(s)</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-item\">\r\n");
      out.write("                <label>Check-In</label>\r\n");
      out.write("                <span>");
      out.print( booking.getInDate() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-item\">\r\n");
      out.write("                <label>Check-Out</label>\r\n");
      out.write("                <span>");
      out.print( booking.getOutDate() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"section-title\">Payment Information</div>\r\n");
      out.write("        <div class=\"info-grid\">\r\n");
      out.write("            <div class=\"info-item\">\r\n");
      out.write("                <label>Payment ID</label>\r\n");
      out.write("                <span>");
      out.print( booking.getPaymentUniqueId() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-item\">\r\n");
      out.write("                <label>Method</label>\r\n");
      out.write("                <span style=\"text-transform: capitalize;\">");
      out.print( booking.getPaymentMethod() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"total-banner\">\r\n");
      out.write("            <label>Total Amount Paid</label>\r\n");
      out.write("            <h2>LKR ");
      out.print( String.format("%.2f", booking.getPrice()) );
      out.write("</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"actions\">\r\n");
      out.write("        <a href=\"/Customer/Dashboard\" class=\"btn btn-home\">Back to Home</a>\r\n");
      out.write("        <button onclick=\"window.print()\" class=\"btn btn-print\">\r\n");
      out.write("            <i class=\"fas fa-print\"></i> Print Receipt\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

    // Optional: Clear the session attribute so it doesn't show up again on refresh
    // session.removeAttribute("lastBooking");

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
