/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2026-02-14 10:16:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Customer;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.net.URLEncoder;
import java.util.List;
import java.util.Map;

public final class Dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Ocean View</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"./css/Dashboard.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"top-bar\">\r\n");
      out.write("            <div class=\"auth-links\">\r\n");
      out.write("                <a class=\"auth-link dropdown-toggle\">\r\n");
      out.write("                    <span class=\"account-icon\"><i class=\"fas fa-user\"></i> My Account</span>\r\n");
      out.write("                    <div class=\"dropdown-content\">\r\n");
      out.write("                        <a href=\"#\">Welcome, User</a>\r\n");
      out.write("                        <a href=\"/Customer/EditProfile\">Profile</a>\r\n");
      out.write("                        <a href=\"/Customer/History\">My Orders</a>\r\n");
      out.write("                        <a href=\"/Customer/Guidelines.html\">Guidelines</a>\r\n");
      out.write("                        <a href=\"/Customer/Signing.jsp\">Logout</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"/Customer/Guidelines.html\" class=\"auth-link\"><span>Guidelines</span><i class=\"fas fa-tag\"></i></a>\r\n");
      out.write("                <a href=\"/Customer/Contact.html\" class=\"auth-link\"><span>Help & Contact</span><i class=\"fas fa-question-circle\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"logo-search\">\r\n");
      out.write("            <a href=\"#\" class=\"logo\">Ocean View Resort</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"main-menu\" id=\"navbar\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"/Customer/About.html\">About Us</a></li>\r\n");
      out.write("\r\n");
      out.write("                <!-- Categories should be dynamically generated here -->\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"menu-icon\" onclick=\"toggleSidebar()\">?</div>\r\n");
      out.write("        <div class=\"sidebar\" id=\"sidebar\">\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeSidebar()\">Ã</a>\r\n");
      out.write("                    <li><a href=\"about.php\">About Us</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Saved</a></li>\r\n");
      out.write("                    <!-- Categories should be dynamically generated here -->\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- Image slider container -->\r\n");
      out.write("    <div class=\"image-slider\">\r\n");
      out.write("        <img src=\"/Slider/slider.jpg\" alt=\"Image 1\" class=\"slider-image\">\r\n");
      out.write("        <div class=\"slide-content\" id=\"slide1\"></div>\r\n");
      out.write("\r\n");
      out.write("        <img src=\"/Slider/sliders2.jpg\" alt=\"Image 2\" class=\"slider-image\">\r\n");
      out.write("        <div class=\"slide-content\" id=\"slide2\"></div>\r\n");
      out.write("\r\n");
      out.write("        <img src=\"/Slider/slider3.jpg\" alt=\"Image 2\" class=\"slider-image\">\r\n");
      out.write("         <div class=\"slide-content\" id=\"slide2\"></div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Slider buttons -->\r\n");
      out.write("        <button class=\"slider-button prev-button\">&#10094;</button>\r\n");
      out.write("        <button class=\"slider-button next-button\">&#10095;</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"category-section\">\r\n");
      out.write("    <h2>Explore Popular Room Categories</h2>\r\n");
      out.write("    <div class=\"categories\">\r\n");
      out.write("        ");

        // Get the vehicles list from the request attribute
        List<Map<String, String>> vehicles = (List<Map<String, String>>) request.getAttribute("rooms");

        // Check if vehicles list is null or empty
        if (vehicles == null || vehicles.isEmpty()) {
        
      out.write("\r\n");
      out.write("            <p>No Room Categories found in the database.</p>\r\n");
      out.write("        ");

        } else {
            // Loop through each vehicle and display its information
            for (Map<String, String> vehicle : vehicles) {
        
      out.write("\r\n");
      out.write("            <!-- The link redirects to Vehicle_Category.jsp with the vehicle name as a query parameter -->\r\n");
      out.write("            <a href=\"/Customer/RoomProducts?roomType=");
      out.print( URLEncoder.encode(vehicle.get("roomName"), "UTF-8") );
      out.write("\" class=\"category-item\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3>");
      out.print( vehicle.get("roomName") );
      out.write("</h3>\r\n");
      out.write("                    <img src=\"http://localhost:8080/");
      out.print( vehicle.get("image") );
      out.write("\" alt=\"");
      out.print( vehicle.get("roomName") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </a>\r\n");
      out.write("        ");

            } // End of for loop
        }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    let currentIndex = 0;\r\n");
      out.write("    const images = document.querySelectorAll('.slider-image');\r\n");
      out.write("    const slideContents = document.querySelectorAll('.slide-content');\r\n");
      out.write("    const prevButton = document.querySelector('.prev-button');\r\n");
      out.write("    const nextButton = document.querySelector('.next-button');\r\n");
      out.write("\r\n");
      out.write("    function changeSlide(direction) {\r\n");
      out.write("        // Hide the current image by moving it out of view\r\n");
      out.write("        images[currentIndex].style.left = direction === 'next' ? '-100%' : '100%';\r\n");
      out.write("        images[currentIndex].style.zIndex = 1;  // Move the current image behind\r\n");
      out.write("        slideContents[currentIndex].classList.remove('active'); // Hide the current content\r\n");
      out.write("\r\n");
      out.write("        // Move the next image into view\r\n");
      out.write("        const nextIndex = (currentIndex + (direction === 'next' ? 1 : -1) + images.length) % images.length;\r\n");
      out.write("        images[nextIndex].style.left = '0';\r\n");
      out.write("        images[nextIndex].style.zIndex = 2;  // Bring the next image to the front\r\n");
      out.write("        slideContents[nextIndex].classList.add('active'); // Show the next content\r\n");
      out.write("\r\n");
      out.write("        // Update current index\r\n");
      out.write("        currentIndex = nextIndex;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Button click listeners\r\n");
      out.write("    prevButton.addEventListener('click', () => changeSlide('prev'));\r\n");
      out.write("    nextButton.addEventListener('click', () => changeSlide('next'));\r\n");
      out.write("\r\n");
      out.write("    // Initially show the first image and content\r\n");
      out.write("    images[currentIndex].style.left = '0';\r\n");
      out.write("    images[currentIndex].style.zIndex = 2;\r\n");
      out.write("    slideContents[currentIndex].classList.add('active');\r\n");
      out.write("\r\n");
      out.write("    // Auto change slide every 5 seconds\r\n");
      out.write("    setInterval(() => changeSlide('next'), 5000);\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
