/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2026-02-05 20:37:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Customer;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Customer.CService.PaymentClass;
import java.util.ArrayList;
import java.text.DecimalFormat;

public final class Payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("Customer.CService.PaymentClass");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Payment History</title>\r\n");
      out.write("        <!-- Link to Bootstrap CSS -->\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            /* Custom CSS for color scheme */\r\n");
      out.write("            .pay-button {\r\n");
      out.write("                background-color: #0073bb;\r\n");
      out.write("                color: white;\r\n");
      out.write("                border: none;\r\n");
      out.write("                padding: 5px 10px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("            }\r\n");
      out.write("            .pay-button:hover {\r\n");
      out.write("                background-color: #5196c1;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Modal Styles */\r\n");
      out.write("            .modal-content {\r\n");
      out.write("                background-color: white;\r\n");
      out.write("                margin: 15% auto;\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("                border: 1px solid #888;\r\n");
      out.write("                width: 30%;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                border-radius: 8px;\r\n");
      out.write("            }\r\n");
      out.write("            .modal button {\r\n");
      out.write("                margin: 5px;\r\n");
      out.write("                padding: 10px 15px;\r\n");
      out.write("                border: none;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("            }\r\n");
      out.write("            .credit-btn { background-color: #007bff; color: white; }\r\n");
      out.write("            .debit-btn { background-color: #17a2b8; color: white; }\r\n");
      out.write("            .cash-btn { background-color: #28a745; color: white; }\r\n");
      out.write("            .close-btn { background-color: red; color: white; }\r\n");
      out.write("            .submit-btn {\r\n");
      out.write("                background-color: #28a745;\r\n");
      out.write("                color: white;\r\n");
      out.write("                padding: 10px 15px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("            }\r\n");
      out.write("            .submit-btn:hover {\r\n");
      out.write("                background-color: #218838;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Back button */\r\n");
      out.write("            .back-btn {\r\n");
      out.write("                background-color: #0073bb;\r\n");
      out.write("                color: white;\r\n");
      out.write("                padding: 8px 15px;\r\n");
      out.write("                border: none;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("            }\r\n");
      out.write("            .back-btn:hover {\r\n");
      out.write("                background-color: #5196c1;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2>Payment History</h2>\r\n");
      out.write("\r\n");
      out.write("            <table class=\"table table-bordered\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Order ID</th>\r\n");
      out.write("                        <th>Vehicle Name</th>\r\n");
      out.write("                        <th>Booked Date</th>\r\n");
      out.write("                        <th>Customer Name</th>\r\n");
      out.write("                        <th>Fine</th> <!-- New Fine column -->\r\n");
      out.write("                        <th>Fare</th> <!-- Fare column -->\r\n");
      out.write("                        <th>Total Fare with Fine</th> <!-- Total Fare with Fine column -->\r\n");
      out.write("                        <th>Action</th>\r\n");
      out.write("                        <th>Status</th> <!-- New Status column -->\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");

                    ArrayList<PaymentClass> historyList = (ArrayList<PaymentClass>) request.getAttribute("historyList");

                    if (historyList != null && !historyList.isEmpty()) {
                        // DecimalFormat to format fine and fare to 2 decimal places
                        DecimalFormat df = new DecimalFormat("0.00");

                        for (PaymentClass history : historyList) {
                            String status = history.getStatus(); // Assuming there's a getStatus method
                            double fine = history.getFine(); // Get fine value
                            double fare = history.getTotal(); // Get fare value
                            double totalFine = fine + fare; // Fine + Total Fare

                            // Format the values
                            String fineFormatted = df.format(fine);
                            String fareFormatted = df.format(fare);
                            String totalFineFormatted = df.format(totalFine);
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( history.getOrderId() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( history.getVehicleName() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( history.getCreatedat() );
      out.write("</td> <!-- Assuming createdat is the booking date -->\r\n");
      out.write("                        <td>");
      out.print( history.getCustomeremail() );
      out.write("</td>\r\n");
      out.write("                        <td>Rs. ");
      out.print( fineFormatted );
      out.write("</td> <!-- Fine -->\r\n");
      out.write("                        <td>Rs. ");
      out.print( fareFormatted );
      out.write("</td> <!-- Total Fare -->\r\n");
      out.write("                        <td>Rs. ");
      out.print( totalFineFormatted );
      out.write("</td> <!-- Total Fare with Fine -->\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            ");
 if (!"Completed".equals(status)) { 
      out.write("\r\n");
      out.write("                                <button class=\"pay-button\" id=\"payButton_");
      out.print( history.getOrderId() );
      out.write("\" onclick=\"openPaymentModal('");
      out.print( history.getOrderId() );
      out.write("', '");
      out.print( history.getTotal() );
      out.write("', this)\">Pay</button>\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <!-- Display \"Paid\" label if already completed -->\r\n");
      out.write("                                <label id=\"paidLabel_");
      out.print( history.getOrderId() );
      out.write("\" style=\"color: green; font-weight: bold; display: inline;\">Paid</label>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            ");
      out.print( "Completed".equals(status) ? "Paid" : "Unpaid" );
      out.write(" <!-- Display the status in the new column -->\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                        } // End of loop
                    } else {
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"9\" style=\"text-align: center;\">No payment history found.</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                    }
                    
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            <button class=\"back-btn\" onclick=\"window.history.back();\">Back</button>\r\n");
      out.write("\r\n");
      out.write("            <!-- Payment Method Modal -->\r\n");
      out.write("            <div id=\"paymentModal\" class=\"modal\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <h3>Select Payment Method</h3>\r\n");
      out.write("                    <form id=\"paymentForm\" action=\"ProcessPaymentServlet\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"orderIdInput\" name=\"orderId\" value=\"\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"paymentMethodInput\" name=\"paymentMethod\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"totalAmountInput\" name=\"total_amount\">\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"creditFields\" style=\"display:none;\">\r\n");
      out.write("                            <label>Card Number:</label>\r\n");
      out.write("                            <input type=\"text\" name=\"cardNumber\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("                            <label>Expiration Date:</label>\r\n");
      out.write("                            <input type=\"month\" name=\"expiryDate\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("                            <label>CVV:</label>\r\n");
      out.write("                            <input type=\"password\" name=\"cvv\" required><br><br>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <button type=\"button\" class=\"credit-btn\" onclick=\"submitPayment('Credit')\">Credit</button>\r\n");
      out.write("                        <button type=\"button\" class=\"debit-btn\" onclick=\"submitPayment('Debit')\">Debit</button>\r\n");
      out.write("                        <button type=\"button\" class=\"cash-btn\" onclick=\"submitPayment('Cash')\">Cash</button>\r\n");
      out.write("                        <button type=\"button\" class=\"close-btn\" onclick=\"closeModal()\">Cancel</button>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Submit button for Credit and Debit -->\r\n");
      out.write("                        <button type=\"submit\" id=\"submitPaymentBtn\" class=\"submit-btn\" style=\"display:none;\">Submit Payment</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                function openPaymentModal(orderId, totalAmount, button) {\r\n");
      out.write("                    // Disable the button to prevent multiple clicks\r\n");
      out.write("                    button.disabled = true;\r\n");
      out.write("                    button.innerHTML = \"Processing...\"; // Change button text to indicate processing\r\n");
      out.write("                    document.getElementById('orderIdInput').value = orderId;\r\n");
      out.write("                    document.getElementById('totalAmountInput').value = totalAmount;\r\n");
      out.write("                    document.getElementById('paymentModal').style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("                    // Store button ID for later re-enabling\r\n");
      out.write("                    document.getElementById('paymentForm').setAttribute('data-button-id', button.id);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                function closeModal() {\r\n");
      out.write("                    document.getElementById('paymentModal').style.display = 'none';\r\n");
      out.write("\r\n");
      out.write("                    // Re-enable the button when the modal is closed\r\n");
      out.write("                    var buttonId = document.getElementById('paymentForm').getAttribute('data-button-id');\r\n");
      out.write("                    if (buttonId) {\r\n");
      out.write("                        var button = document.getElementById(buttonId);\r\n");
      out.write("                        button.disabled = false;  // Re-enable the button\r\n");
      out.write("                        button.innerHTML = \"Pay\"; // Reset the button text to \"Pay\"\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                function submitPayment(method) {\r\n");
      out.write("                    var orderId = document.getElementById('orderIdInput').value;\r\n");
      out.write("                    var totalAmount = document.getElementById('totalAmountInput').value;\r\n");
      out.write("\r\n");
      out.write("                    document.getElementById('paymentMethodInput').value = method;\r\n");
      out.write("\r\n");
      out.write("                    // Show card fields for Credit/Debit\r\n");
      out.write("                    if (method === 'Credit' || method === 'Debit') {\r\n");
      out.write("                        document.getElementById('creditFields').style.display = 'block';\r\n");
      out.write("                        document.getElementById('submitPaymentBtn').style.display = 'inline';  // Show Submit button\r\n");
      out.write("                    } else {\r\n");
      out.write("                        document.getElementById('creditFields').style.display = 'none';\r\n");
      out.write("                        document.getElementById('submitPaymentBtn').style.display = 'none';  // Hide Submit button for Cash\r\n");
      out.write("                        // Submit form for Cash payment directly\r\n");
      out.write("                        document.getElementById('paymentForm').submit();\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // Hide the \"Pay\" button and show \"Paid\" label after payment submission\r\n");
      out.write("                    document.getElementById('payButton_' + orderId).style.display = 'none';\r\n");
      out.write("                    document.getElementById('paidLabel_' + orderId).style.display = 'inline';  // Show \"Paid\" label\r\n");
      out.write("                }\r\n");
      out.write("            </script>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
