/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2026-02-04 18:38:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Customer;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import org.Ocean_View.Admin.Entity.Room;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.net.URLEncoder;

public final class RoomCategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String buildImageUrl(String imagePath, HttpServletRequest request) {
        if (imagePath == null || imagePath.trim().isEmpty()) {
            return request.getContextPath() + "/Customer/default-room.jpg";
        }
        imagePath = imagePath.trim();
        if (imagePath.startsWith("http")) return imagePath;
        return request.getContextPath() + (imagePath.startsWith("/") ? "" : "/") + imagePath;
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("org.Ocean_View.Admin.Entity.Room");
    _jspx_imports_classes.add("java.util.LinkedHashSet");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Room Details - ");
      out.print( request.getParameter("roomType") );
      out.write("</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/RoomCategory.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/flatpickr\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h1><i class=\"fas fa-hotel\"></i>\r\n");
      out.write("                ");
      out.print( request.getParameter("roomType") != null ?
                   request.getParameter("roomType") : "All" );
      out.write(" Rooms\r\n");
      out.write("            </h1>\r\n");
      out.write("            <p>Find the perfect accommodation for your stay</p>\r\n");
      out.write("            <a href=\"javascript:history.back()\" class=\"back-button\">\r\n");
      out.write("                <i class=\"fas fa-arrow-left\"></i> Back to Categories\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");

            // Get the list of rooms from request attribute
            List<Room> rooms = (List<Room>) request.getAttribute("rooms");
            String roomType = request.getParameter("roomType");

            if (rooms == null || rooms.isEmpty()) {
        
      out.write("\r\n");
      out.write("            <div class=\"no-rooms\">\r\n");
      out.write("                <i class=\"fas fa-door-closed\"></i>\r\n");
      out.write("                <h2>No ");
      out.print( roomType != null ? roomType : "" );
      out.write(" Rooms Available</h2>\r\n");
      out.write("                <p>We're sorry, but there are currently no ");
      out.print( roomType != null ? roomType : "" );
      out.write(" rooms available for booking.</p>\r\n");
      out.write("                <p>Please check back later or explore other room categories.</p>\r\n");
      out.write("                <a href=\"index.jsp\" class=\"btn btn-book\" style=\"margin-top: 20px; display: inline-block;\">\r\n");
      out.write("                    <i class=\"fas fa-home\"></i> Back to Home\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");

            } else {
        
      out.write("\r\n");
      out.write("            <div class=\"rooms-grid\">\r\n");
      out.write("                ");

                    for (Room room : rooms) {
                        // FIX: Sanitize ID so JavaScript can find the correct data div for every unique room
                        String safeId = room.getUniqueId().replaceAll("[^a-zA-Z0-9]", "");

                        List<String> images = room.getImageList();
                        List<String> uniqueImages = new ArrayList<>();
                        HashSet<String> seen = new HashSet<>();

                        if (images != null) {
                            for (String img : images) {
                                String trimmedImg = img.trim();
                                if (!trimmedImg.isEmpty() && !seen.contains(trimmedImg)) {
                                    seen.add(trimmedImg);
                                    uniqueImages.add(trimmedImg);
                                }
                            }
                        }

                        String mainImage = uniqueImages.isEmpty() ? "/Customer/default-room.jpg" : uniqueImages.get(0);
                        String mainImageUrl = buildImageUrl(mainImage, request);
                
      out.write("\r\n");
      out.write("                    <div class=\"room-card\" id=\"room-card-");
      out.print( safeId );
      out.write("\">\r\n");
      out.write("                        <div class=\"room-image-container\">\r\n");
      out.write("                            <div class=\"main-image-wrapper\">\r\n");
      out.write("                                <img src=\"");
      out.print( mainImageUrl );
      out.write("\"\r\n");
      out.write("                                     alt=\"");
      out.print( room.getRoomType() );
      out.write("\"\r\n");
      out.write("                                     class=\"room-main-image\"\r\n");
      out.write("                                     onclick=\"openImageModal('");
      out.print( safeId );
      out.write("', 0)\"\r\n");
      out.write("                                     onerror=\"this.onerror=null; this.src='");
      out.print( request.getContextPath() );
      out.write("/Customer/default-room.jpg';\"\r\n");
      out.write("                                     loading=\"lazy\">\r\n");
      out.write("\r\n");
      out.write("                                ");
 if (uniqueImages.size() > 1) { 
      out.write("\r\n");
      out.write("                                    <div class=\"thumbnail-preview\">\r\n");
      out.write("                                        ");

                                            // FIX: Corrected loop and ID reference for thumbnails
                                            int thumbnailsToShow = Math.min(uniqueImages.size() - 1, 3);
                                            for (int i = 1; i <= thumbnailsToShow; i++) {
                                                String thumbImageUrl = buildImageUrl(uniqueImages.get(i), request);
                                        
      out.write("\r\n");
      out.write("                                            <div class=\"thumbnail-item\" onclick=\"openImageModal('");
      out.print( safeId );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( i );
      out.write(")\">\r\n");
      out.write("                                                <img src=\"");
      out.print( thumbImageUrl );
      out.write("\"\r\n");
      out.write("                                                     alt=\"Thumbnail ");
      out.print( i );
      out.write("\"\r\n");
      out.write("                                                     class=\"thumbnail-image\"\r\n");
      out.write("                                                     onerror=\"this.onerror=null; this.src='");
      out.print( request.getContextPath() );
      out.write("/Customer/default-room.jpg';\"\r\n");
      out.write("                                                     loading=\"lazy\">\r\n");
      out.write("                                                ");

                                                    if (i == thumbnailsToShow && uniqueImages.size() > thumbnailsToShow + 1) {
                                                        int remainingImages = uniqueImages.size() - (thumbnailsToShow + 1);
                                                
      out.write("\r\n");
      out.write("                                                    <div class=\"more-images-overlay\">\r\n");
      out.write("                                                        +");
      out.print( remainingImages );
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                ");
 } 
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"room-details\">\r\n");
      out.write("                            <h2 class=\"room-title\">\r\n");
      out.write("                                ");
      out.print( room.getUniqueId() );
      out.write("\r\n");
      out.write("                                <span class=\"status-badge ");
      out.print( room.getStatus().equalsIgnoreCase("Active") ? "status-available" : "status-booked" );
      out.write("\">\r\n");
      out.write("                                    <i class=\"fas fa-");
      out.print( room.getStatus().equalsIgnoreCase("Active") ? "check-circle" : "times-circle" );
      out.write("\"></i>\r\n");
      out.write("                                    ");
      out.print( room.getStatus() );
      out.write("\r\n");
      out.write("                                </span>\r\n");
      out.write("\r\n");
      out.write("                            </h2>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"room-info\">\r\n");
      out.write("                                <span class=\"info-label\"><i class=\"fas fa-users\"></i> Capacity:</span>\r\n");
      out.write("                                <span class=\"info-value\">");
      out.print( room.getNoOfPeople() );
      out.write(" People</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"room-info\">\r\n");
      out.write("                                <span class=\"info-label\"><i class=\"fas fa-calendar-alt\"></i> Created:</span>\r\n");
      out.write("                                <span class=\"info-value\">\r\n");
      out.write("                                    ");
      out.print( room.getCreated_at() != null ? room.getCreated_at().toLocalDate() : "N/A" );
      out.write("\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            ");
 if (room.getDescription() != null && !room.getDescription().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"room-info\">\r\n");
      out.write("                                <span class=\"info-label\"><i class=\"fas fa-align-left\"></i> Description:</span>\r\n");
      out.write("                                <span class=\"info-value\">");
      out.print( room.getDescription() );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"price-tag\">\r\n");
      out.write("                                <i class=\"fas fa-tag\"></i> LKR.");
      out.print( room.getPrice() );
      out.write(" / night\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            ");
 if (room.getFacilities() != null && !room.getFacilities().isEmpty()) { 
      out.write("\r\n");
      out.write("                            <div class=\"facilities-section\">\r\n");
      out.write("                                <h3 class=\"section-title\"><i class=\"fas fa-concierge-bell\"></i> Facilities</h3>\r\n");
      out.write("                                <ul class=\"facilities-list\">");
      out.print( room.getFacilities() );
      out.write("</ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                              ");
 if (room.getRules() != null && !room.getRules().isEmpty()) { 
      out.write("\r\n");
      out.write("                                                         <div class=\"rules-section\">\r\n");
      out.write("                                                             <h3 class=\"section-title\">\r\n");
      out.write("                                                                 <i class=\"fas fa-clipboard-list\"></i> Rules\r\n");
      out.write("                                                             </h3>\r\n");
      out.write("                                                             <ul class=\"rules-list\">\r\n");
      out.write("                                                                ");
      out.print( room.getRules() );
      out.write("\r\n");
      out.write("                                                             </ul>\r\n");
      out.write("                                                         </div>\r\n");
      out.write("                                                         ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                         ");
 if (room.getFine() != null && !room.getFine().isEmpty()) { 
      out.write("\r\n");
      out.write("                                                         <div class=\"fine-section\">\r\n");
      out.write("                                                             <h3 class=\"section-title\">\r\n");
      out.write("                                                                 <i class=\"fas fa-exclamation-triangle\"></i> Fine Price\r\n");
      out.write("                                                             </h3>\r\n");
      out.write("                                                             <p>LKR. ");
      out.print( room.getFine() );
      out.write("</p>\r\n");
      out.write("                                                         </div>\r\n");
      out.write("                                                         ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div id=\"room-images-");
      out.print( safeId );
      out.write("\" style=\"display: none;\">\r\n");
      out.write("                                ");
      out.print( String.join(",", uniqueImages) );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"action-buttons\">\r\n");
      out.write("\r\n");
      out.write("                                   <button class=\"btn btn-book\"\r\n");
      out.write("                                           onclick=\"openBookingModal('");
      out.print( room.getUniqueId() );
      out.write("', '");
      out.print( room.getPrice() );
      out.write("', '");
      out.print( room.getRoomType() );
      out.write("')\">\r\n");
      out.write("                                       <i class=\"fas fa-calendar-check\"></i> Book Now\r\n");
      out.write("                                   </button>\r\n");
      out.write("\r\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/Customer/Enquiry.jsp?roomId=");
      out.print( room.getUniqueId() );
      out.write("&roomType=");
      out.print( URLEncoder.encode(room.getRoomType(), "UTF-8") );
      out.write("\"\r\n");
      out.write("                                   class=\"btn btn-enquiry\">\r\n");
      out.write("                                    <i class=\"fas fa-question-circle\"></i> Enquire\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"imageModal\" class=\"modal\">\r\n");
      out.write("        <span class=\"close\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("        <a class=\"prev\" onclick=\"changeImage(-1)\">&#10094;</a>\r\n");
      out.write("        <a class=\"next\" onclick=\"changeImage(1)\">&#10095;</a>\r\n");
      out.write("        <img class=\"modal-content\" id=\"modalImage\">\r\n");
      out.write("        <div id=\"caption\" class=\"caption\"></div>\r\n");
      out.write("        <div id=\"imageCounter\" style=\"color: white; text-align: center; margin-top: 10px;\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        let checkInPicker = null;\r\n");
      out.write("        let checkOutPicker = null;\r\n");
      out.write("\r\n");
      out.write("        let currentRoomId = '';\r\n");
      out.write("        let currentImages = [];\r\n");
      out.write("        let currentImageIndex = 0;\r\n");
      out.write("        const contextPath = '");
      out.print( request.getContextPath() );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("        function buildJsImageUrl(imagePath) {\r\n");
      out.write("            imagePath = imagePath.trim();\r\n");
      out.write("            if (imagePath.startsWith('http')) return imagePath;\r\n");
      out.write("            const cleanPath = imagePath.startsWith('/') ? imagePath : '/' + imagePath;\r\n");
      out.write("            // Ensure we don't double the context path\r\n");
      out.write("            return cleanPath.startsWith(contextPath) ? window.location.origin + cleanPath : window.location.origin + contextPath + cleanPath;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function openImageModal(roomId, imageIndex) {\r\n");
      out.write("            const imageDataDiv = document.getElementById('room-images-' + roomId);\r\n");
      out.write("            if (!imageDataDiv) return;\r\n");
      out.write("\r\n");
      out.write("            const imagePaths = imageDataDiv.textContent.split(',');\r\n");
      out.write("            currentImages = imagePaths.map(img => buildJsImageUrl(img));\r\n");
      out.write("            currentRoomId = roomId;\r\n");
      out.write("            currentImageIndex = parseInt(imageIndex) || 0;\r\n");
      out.write("\r\n");
      out.write("            document.getElementById('imageModal').style.display = \"block\";\r\n");
      out.write("            document.body.style.overflow = \"hidden\";\r\n");
      out.write("            updateModalImage();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function closeModal() {\r\n");
      out.write("            document.getElementById('imageModal').style.display = \"none\";\r\n");
      out.write("            document.body.style.overflow = \"auto\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function changeImage(direction) {\r\n");
      out.write("            if (currentImages.length === 0) return;\r\n");
      out.write("            currentImageIndex = (currentImageIndex + direction + currentImages.length) % currentImages.length;\r\n");
      out.write("            updateModalImage();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function updateModalImage() {\r\n");
      out.write("            if (currentImages.length === 0) return;\r\n");
      out.write("            const modalImage = document.getElementById('modalImage');\r\n");
      out.write("            const caption = document.getElementById('caption');\r\n");
      out.write("            const counter = document.getElementById('imageCounter');\r\n");
      out.write("\r\n");
      out.write("            modalImage.src = currentImages[currentImageIndex];\r\n");
      out.write("            caption.innerHTML = `Room: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentRoomId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" | Image ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentImageIndex + 1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" of ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentImages.length}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            counter.innerHTML = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentImageIndex + 1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentImages.length}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        window.onclick = function(event) {\r\n");
      out.write("            if (event.target == document.getElementById('imageModal')) closeModal();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        document.addEventListener('keydown', function(event) {\r\n");
      out.write("            if (document.getElementById('imageModal').style.display === 'block') {\r\n");
      out.write("                if (event.key === 'Escape') closeModal();\r\n");
      out.write("                if (event.key === 'ArrowLeft') changeImage(-1);\r\n");
      out.write("                if (event.key === 'ArrowRight') changeImage(1);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        async function openBookingModal(roomId, price,category) {\r\n");
      out.write("\r\n");
      out.write("        unavailableDates = [];\r\n");
      out.write("\r\n");
      out.write("            document.getElementById('modalRoomId').value = roomId;\r\n");
      out.write("            document.getElementById('modalRoomPrice').value = price;\r\n");
      out.write("            document.getElementById('modalRoomCategory').value = category;\r\n");
      out.write("            document.getElementById('bookingModal').style.display = \"block\";\r\n");
      out.write("\r\n");
      out.write("            // Set min date to Today\r\n");
      out.write("            const today = new Date().toISOString().split('T')[0];\r\n");
      out.write("            const checkInInput = document.getElementById('checkIn');\r\n");
      out.write("            const checkOutInput = document.getElementById('checkOut');\r\n");
      out.write("\r\n");
      out.write("           try {\r\n");
      out.write("                   const response = await fetch(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Customer/GetBookedDates?roomId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("                   unavailableDates = await response.json();\r\n");
      out.write("                   console.log(\"Booked dates for this room:\", unavailableDates);\r\n");
      out.write("               } catch (err) {\r\n");
      out.write("                   console.error(\"Failed to fetch booked dates\", err);\r\n");
      out.write("               }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function closeBookingModal() {\r\n");
      out.write("            document.getElementById('bookingModal').style.display = \"none\";\r\n");
      out.write("            document.getElementById('bookingForm').reset();\r\n");
      out.write("            toggleCardDetails(false);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function calculateTotal() {\r\n");
      out.write("            const checkInInput = document.getElementById('checkIn');\r\n");
      out.write("            const checkOutInput = document.getElementById('checkOut');\r\n");
      out.write("            const checkInVal = checkInInput.value;\r\n");
      out.write("            const checkOutVal = checkOutInput.value;\r\n");
      out.write("            const pricePerNight = parseFloat(document.getElementById('modalRoomPrice').value) || 0;\r\n");
      out.write("\r\n");
      out.write("            if (checkInVal) {\r\n");
      out.write("                checkOutInput.setAttribute('min', checkInVal);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (checkInVal && checkOutVal) {\r\n");
      out.write("                const userIn = new Date(checkInVal);\r\n");
      out.write("                const userOut = new Date(checkOutVal);\r\n");
      out.write("\r\n");
      out.write("                // --- OVERLAP VALIDATION LOGIC ---\r\n");
      out.write("                const isOverlap = unavailableDates.some(range => {\r\n");
      out.write("                    const bookedIn = new Date(range.checkIn);\r\n");
      out.write("                    const bookedOut = new Date(range.checkOut);\r\n");
      out.write("                    // Logic: A booking overlaps if (UserStart < BookedEnd) AND (UserEnd > BookedStart)\r\n");
      out.write("                    console.table(unavailableDates);\r\n");
      out.write("                    return (userIn < bookedOut && userOut > bookedIn);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                if (isOverlap) {\r\n");
      out.write("                    alert(\"â Conflict: This room is already booked during the selected dates. Please choose another stay period.\");\r\n");
      out.write("                    checkInInput.value = \"\";\r\n");
      out.write("                    checkOutInput.value = \"\";\r\n");
      out.write("                    resetTotals();\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                // --- END VALIDATION ---\r\n");
      out.write("\r\n");
      out.write("                if (userOut > userIn) {\r\n");
      out.write("                    const diffTime = Math.abs(userOut - userIn);\r\n");
      out.write("                    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));\r\n");
      out.write("                    document.getElementById('displayDays').value = diffDays;\r\n");
      out.write("                    document.getElementById('displayTotal').value = (diffDays * pricePerNight).toFixed(2);\r\n");
      out.write("                } else {\r\n");
      out.write("                    resetTotals();\r\n");
      out.write("                }\r\n");
      out.write("            } else {\r\n");
      out.write("                resetTotals();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function resetTotals() {\r\n");
      out.write("            document.getElementById('displayDays').value = \"0\";\r\n");
      out.write("            document.getElementById('displayTotal').value = \"0.00\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function toggleCardDetails(show) {\r\n");
      out.write("            document.getElementById('cardDetails').style.display = show ? \"block\" : \"none\";\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"bookingModal\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content booking-form-card\">\r\n");
      out.write("            <span class=\"close\" onclick=\"closeBookingModal()\">&times;</span>\r\n");
      out.write("            <h2>Confirm Your Booking</h2>\r\n");
      out.write("            <form id=\"bookingForm\" action=\"ProcessBooking\" method=\"POST\">\r\n");
      out.write("                <input type=\"hidden\" name=\"roomId\" id=\"modalRoomId\">\r\n");
      out.write("                <input type=\"hidden\" name=\"roomPrice\" id=\"modalRoomPrice\">\r\n");
      out.write("                <input type=\"hidden\" name=\"roomCategory\" id=\"modalRoomCategory\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label>Check-in Date:</label>\r\n");
      out.write("                    <input type=\"date\" name=\"checkIn\" id=\"checkIn\" required onchange=\"calculateTotal()\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label>Check-out Date:</label>\r\n");
      out.write("                    <input type=\"date\" name=\"checkOut\" id=\"checkOut\" required onchange=\"calculateTotal()\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"booking-summary\">\r\n");
      out.write("                   <div class=\"summary-item\">\r\n");
      out.write("                       <label>Total Days</label>\r\n");
      out.write("                       <div class=\"input-wrapper\">\r\n");
      out.write("                           <input type=\"text\" name=\"totalDays\" id=\"displayDays\" value=\"0\" readonly>\r\n");
      out.write("                           <span>Days</span>\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("\r\n");
      out.write("                   <div class=\"summary-item\">\r\n");
      out.write("                       <label>Total Price</label>\r\n");
      out.write("                       <div class=\"input-wrapper\">\r\n");
      out.write("                           <span class=\"currency\">LKR</span>\r\n");
      out.write("                           <input type=\"text\" name=\"totalPrice\" id=\"displayTotal\" value=\"0.00\" readonly class=\"total-amount\">\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"payment-section\">\r\n");
      out.write("                    <h3>Payment Method</h3>\r\n");
      out.write("                    <div class=\"payment-options\">\r\n");
      out.write("                        <label><input type=\"radio\" name=\"paymentMethod\" value=\"cash\" checked onclick=\"toggleCardDetails(false)\"> Cash</label>\r\n");
      out.write("                        <label><input type=\"radio\" name=\"paymentMethod\" value=\"card\" onclick=\"toggleCardDetails(true)\"> Debit/Credit Card</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"cardDetails\" style=\"display: none; margin-top: 15px;\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"Card Number\" class=\"form-input\">\r\n");
      out.write("                        <div style=\"display: flex; gap: 10px; margin-top: 10px;\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"MM/YY\" style=\"flex: 1;\" class=\"form-input\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"CVV\" style=\"flex: 1;\" class=\"form-input\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-book\" style=\"width: 100%; margin-top: 20px;\">\r\n");
      out.write("                    Confirm & Pay\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
