/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2026-01-30 12:50:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Customer;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;
import java.util.List;

public final class RoomCategory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Vehicle Category</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("      /* General Styles */\r\n");
      out.write("      body {\r\n");
      out.write("            background: #85C1FF; /* Lighter Blue Background */\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            color: #333; /* Darker text for better readability */\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Header */\r\n");
      out.write("        h1 {\r\n");
      out.write("            color: #333; /* Dark text for contrast */\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Vehicle Cards */\r\n");
      out.write("       /* Vehicle Card */\r\n");
      out.write(".vehicle-card {\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    max-width: 300px; /* Adjust the max-width to make the card smaller */\r\n");
      out.write("    margin: 0 auto; /* Center the card horizontally */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        .vehicle-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Vehicle Image */\r\n");
      out.write("        .vehicle-image {\r\n");
      out.write("            max-width: 80%;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            border: 2px solid #ddd;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .vehicle-image:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Vehicle Name and Info */\r\n");
      out.write("        .vehicle-card h3 {\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .vehicle-card p {\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Rent Price */\r\n");
      out.write("        .rentperday {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            color: #28a745;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Footer */\r\n");
      out.write("        .vehicle-card-footer {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .book-now {\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .book-now:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .book-now:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Modal Styles */\r\n");
      out.write("        .modal-content {\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-header {\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-title {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-body {\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-body .form-label {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-body input {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-body input:focus {\r\n");
      out.write("            border-color: #007bff;\r\n");
      out.write("            box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Button Styles */\r\n");
      out.write("        .btn-success {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            background-color: #28a745;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-success:hover {\r\n");
      out.write("            background-color: #218838;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Input Fields */\r\n");
      out.write("        input[type=\"date\"],\r\n");
      out.write("        input[type=\"time\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"date\"]:focus,\r\n");
      out.write("        input[type=\"time\"]:focus {\r\n");
      out.write("            border-color: #007bff;\r\n");
      out.write("            box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Container */\r\n");
      out.write("        .container {\r\n");
      out.write("            padding-top: 50px;\r\n");
      out.write("            padding-bottom: 50px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Search Form Styles */\r\n");
      out.write("        .search-form {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-form input {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-form button {\r\n");
      out.write("            flex-shrink: 0;\r\n");
      out.write("            background-color: #0056b3; /* Blue search button */\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-form button:hover {\r\n");
      out.write("            background-color: #003c82; /* Darker blue on hover */\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container mt-4\">\r\n");
      out.write("        <h1>Vehicle Category: ");
      out.print( request.getParameter("vehicleType") );
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"ProductServlet\" method=\"get\" class=\"search-form mb-4\">\r\n");
      out.write("            <input type=\"hidden\" name=\"vehicleType\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vehicleType}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("            <input type=\"text\" name=\"searchQuery\" placeholder=\"Search by name, brand, or year\" class=\"form-control\" />\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary mt-2\">Search</button>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            ");

                List<Map<String, String>> vehicleDetails = (List<Map<String, String>>) request.getAttribute("vehicleDetails");
                if (vehicleDetails == null || vehicleDetails.isEmpty()) {
            
      out.write("\r\n");
      out.write("                <p>No vehicles found for this category.</p>\r\n");
      out.write("            ");

                } else {
                    for (Map<String, String> vehicle : vehicleDetails) {
                        String vehicleName = vehicle.get("vehicle_name");
                        String vehicleYear = vehicle.get("vehicle_year");
                        String brandName = vehicle.get("brand_name");
                        String fullImagePath = vehicle.get("vehicle_image_path");
                        String vehicleCondition = vehicle.get("vehicle_condition");
                        String mileage = vehicle.get("mileage");
                        String rentperday = vehicle.get("rent_per_day");
                        String color = vehicle.get("color");
            
      out.write("\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"vehicle-card\">\r\n");
      out.write("                        ");
 if (fullImagePath != null && !fullImagePath.isEmpty()) { 
      out.write("\r\n");
      out.write("                            <img src=\"");
      out.print( fullImagePath );
      out.write("\" alt=\"Vehicle Image\" class=\"vehicle-image\">\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <img src=\"default-image.png\" alt=\"Default Vehicle Image\" class=\"vehicle-image\">\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        <h3>");
      out.print( vehicleName );
      out.write("</h3>\r\n");
      out.write("                        <p><strong>Year:</strong> ");
      out.print( vehicleYear );
      out.write("</p>\r\n");
      out.write("                        <p><strong>Brand:</strong> ");
      out.print( brandName );
      out.write("</p>\r\n");
      out.write("                        <p><strong>Condition:</strong> ");
      out.print( vehicleCondition );
      out.write("</p>\r\n");
      out.write("                        <p><strong>Mileage:</strong> ");
      out.print( mileage );
      out.write("</p>\r\n");
      out.write("                        <p><strong>Rent per day:</strong> <span class=\"rentperday\">");
      out.print( rentperday );
      out.write("</span></p>\r\n");
      out.write("                        <p><strong>Color:</strong> ");
      out.print( color );
      out.write("</p>\r\n");
      out.write("                        <div class=\"vehicle-card-footer\">\r\n");
      out.write("                            <button class=\"btn btn-primary book-now\" data-bs-toggle=\"modal\" data-bs-target=\"#bookingModal\"\r\n");
      out.write("                                    data-vehicle=\"");
      out.print( vehicleName );
      out.write("\" data-rent=\"");
      out.print( rentperday );
      out.write("\">\r\n");
      out.write("                                Book Now\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");

                    }
                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal for booking -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"bookingModal\" tabindex=\"-1\" aria-labelledby=\"bookingModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"bookingModalLabel\">Book <span id=\"vehicleName\"></span></h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <form action=\"bookVehicleServlet\" method=\"POST\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"vehicleName\" id=\"hiddenVehicleName\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"rentperday\" id=\"hiddenRentPerDay\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"bookingDate\" class=\"form-label\">Booking Date</label>\r\n");
      out.write("                            <input type=\"date\" class=\"form-control\" name=\"bookingDate\" id=\"bookingDate\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"bookingTime\" class=\"form-label\">Booking Time</label>\r\n");
      out.write("                            <input type=\"time\" class=\"form-control\" name=\"bookingTime\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"returndate\" class=\"form-label\">Return Date</label>\r\n");
      out.write("                            <input type=\"date\" class=\"form-control\" name=\"returndate\" id=\"returndate\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"totalPrice\" class=\"form-label\">Total Price</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"totalPrice\" id=\"totalPrice\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-success\">Confirm Booking</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.querySelectorAll('.book-now').forEach(button => {\r\n");
      out.write("            button.addEventListener('click', function() {\r\n");
      out.write("                var vehicleName = this.getAttribute('data-vehicle');\r\n");
      out.write("                var rentPerDay = this.getAttribute('data-rent');\r\n");
      out.write("\r\n");
      out.write("                document.getElementById('vehicleName').textContent = vehicleName;\r\n");
      out.write("                document.getElementById('hiddenVehicleName').value = vehicleName;\r\n");
      out.write("                document.getElementById('hiddenRentPerDay').value = rentPerDay;\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('bookingDate').addEventListener('change', calculateTotalPrice);\r\n");
      out.write("        document.getElementById('returndate').addEventListener('change', calculateTotalPrice);\r\n");
      out.write("\r\n");
      out.write("        function calculateTotalPrice() {\r\n");
      out.write("            var bookingDateValue = document.getElementById('bookingDate').value;\r\n");
      out.write("            var returnDateValue = document.getElementById('returndate').value;\r\n");
      out.write("            var rentPerDay = parseFloat(document.getElementById('hiddenRentPerDay').value);\r\n");
      out.write("\r\n");
      out.write("            if (bookingDateValue && returnDateValue) {\r\n");
      out.write("                var bookingDate = new Date(bookingDateValue);\r\n");
      out.write("                var returnDate = new Date(returnDateValue);\r\n");
      out.write("\r\n");
      out.write("                if (returnDate > bookingDate) {\r\n");
      out.write("                    var timeDiff = returnDate.getTime() - bookingDate.getTime();\r\n");
      out.write("                    var dayDiff = Math.ceil(timeDiff / (1000 * 3600 * 24));\r\n");
      out.write("                    var totalPrice = dayDiff * rentPerDay;\r\n");
      out.write("                    document.getElementById('totalPrice').value = totalPrice.toFixed(2);\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert('Return date must be after the booking date.');\r\n");
      out.write("document.getElementById('returndate').value = ''; // Clear the return date field\r\n");
      out.write("document.getElementById('totalPrice').value = ''; // Clear total price\r\n");
      out.write("document.getElementById('returndate').focus(); // Focus on return date field\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
